PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pr: <http://purl.org/ontology/prv/core#>
PREFIX metago: <http://model.geneontology.org/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX obo: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX gomodel: <http://model.geneontology.org/>
PREFIX providedBy: <http://purl.org/pav/providedBy>

PREFIX MF: <http://purl.obolibrary.org/obo/GO_0003674>

PREFIX causally_upstream_of_or_within: <http://purl.obolibrary.org/obo/RO_0002418>
PREFIX causally_upstream_of_or_within_negative_effect: <http://purl.obolibrary.org/obo/RO_0004046>
PREFIX causally_upstream_of_or_within_positive_effect: <http://purl.obolibrary.org/obo/RO_0004047>

PREFIX causally_upstream_of: <http://purl.obolibrary.org/obo/RO_0002411>
PREFIX causally_upstream_of_negative_effect: <http://purl.obolibrary.org/obo/RO_0002305>
PREFIX causally_upstream_of_positive_effect: <http://purl.obolibrary.org/obo/RO_0002304>

PREFIX regulates: <http://purl.obolibrary.org/obo/RO_0002211>
PREFIX negatively_regulates: <http://purl.obolibrary.org/obo/RO_0002212>
PREFIX positively_regulates: <http://purl.obolibrary.org/obo/RO_0002213>

PREFIX directly_regulates: <http://purl.obolibrary.org/obo/RO_0002578>
PREFIX directly_positively_regulates: <http://purl.obolibrary.org/obo/RO_0002629>
PREFIX directly_negatively_regulates: <http://purl.obolibrary.org/obo/RO_0002630>

PREFIX directly_activates: <http://purl.obolibrary.org/obo/RO_0002406>
PREFIX indirectly_activates: <http://purl.obolibrary.org/obo/RO_0002407>

PREFIX directly_inhibits: <http://purl.obolibrary.org/obo/RO_0002408>
PREFIX indirectly_inhibits: <http://purl.obolibrary.org/obo/RO_0002409>

PREFIX transitively_provides_input_for: <http://purl.obolibrary.org/obo/RO_0002414>
PREFIX immediately_causally_upstream_of: <http://purl.obolibrary.org/obo/RO_0002412>
PREFIX directly_provides_input_for: <http://purl.obolibrary.org/obo/RO_0002413>

SELECT ?gocam (str(?title) as ?title) (str(COUNT(DISTINCT(?ind_root))) as ?root_mf_count)
          (str(COUNT(DISTINCT(?ind_non_root))) as ?non_root_mf_count)
          # (GROUP_CONCAT(distinct ?orcid;separator="@@") AS ?orcids) 
                            (GROUP_CONCAT(distinct ?name;separator="@@") AS ?names)
                            # (GROUP_CONCAT(distinct ?providedBy;separator="@@") AS ?groupids) 
                            (GROUP_CONCAT(distinct ?providedByLabel;separator="@@") AS ?groupnames)

WHERE 
{
  ?causal1 rdfs:subPropertyOf* causally_upstream_of_or_within: .
  ?causal2 rdfs:subPropertyOf* causally_upstream_of_or_within: .
  {
    GRAPH ?gocam {                 
      ?gocam metago:graphType metago:noctuaCam .
      ?gocam dc:date ?date .
      ?gocam dc:title ?title .
      ?gocam dc:contributor ?orcid .
      ?gocam providedBy: ?providedBy .
      BIND( IRI(?orcid) AS ?orcidIRI ).
      BIND( IRI(?providedBy) AS ?providedByIRI ).
      ?ind1 ?causal1 ?ind2 .     
      ?ind2 ?causal2 ?ind3
    }
    GRAPH ?gocam {
      optional { ?ind_root a MF: } .
      ?ind_non_root a ?mf_non_root_type .
      FILTER(?mf_non_root_type != MF:) .
FILTER(?mf_non_root_type != owl:NamedIndividual)
    }
    ?ind1 rdf:type MF: .
    ?ind2 rdf:type MF: .
    ?ind3 rdf:type MF: .
    ?ind_non_root rdf:type MF: .
    optional {
        ?providedByIRI rdfs:label ?providedByLabel .
    }

    optional { ?orcidIRI rdfs:label ?name }
    BIND(IF(bound(?name), ?name, ?orcid) as ?name) .
  }
  # FILTER(?gocam = gomodel:568b0f9600000284) .
}        
GROUP BY ?gocam ?title
HAVING(COUNT(DISTINCT(?ind_non_root)) > COUNT(DISTINCT(?ind_root)))
ORDER BY ?gocam
